// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwzpdnxgqkoysmammhqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3enBkbnhncWtveXNtYW1taHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODY0MTQsImV4cCI6MjA3Mzk2MjQxNH0.o-s1iIzs8OcbgeMoOe5Ob-ufc0fNR4-Y_VceyHOtK8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});